[package]
name = "spark"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argon2 = "0.4.1"
rand_core = { version = "0.6", features = ["std"] }

rand = "0.8.5"
hex = "0.4.3"
rsa = "0.6.1"
